name: CI
on:
  pull_request:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: olafurpg/setup-scala@v11
      with:
        java-version: adopt@1.11
    - uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Install npm deps
      run: npm ci
    - name: Compile & Test
      run: sbt clean compile test